#!/bin/sh

if [[ "$1" == "-v" ]]; then
  rsync_opts="-v"
else
  rsync_opts=""
fi

# change remote hostname here
remote=barney
ssh_key=$HOME/.ssh/id_rsa_rsync_$remote

backup_dir() {
  echo "Backing up dir $1 to $2..."
  eval nice -n 20 ionice -c 3 -n 7 rsync \
         -auz $rsync_opts $3 \
         -e "ssh -i $ssh_key" \
         "$1/" "$remote:$2"
  return $?
}

# check for lock
if [ -e ~/.lock/backup-$remote ]; then
  echo >&2 "locked!"
  exit 111
fi

touch ~/.lock/backup-$remote

RET=0

backup_dir /home/niklas /mnt/crypt_single1/home/niklas  "--delete --exclude=mnt"
backup_dir /mnt/data /mnt/crypt_single1

# remove lock
rm ~/.lock/backup-$remote

exit $ret

